#server:
#  port: 7001
#
#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.80.100:3306/gulimall_sms?userSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.80.100:8848
#  application:
#    name: gulimall-coupon
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
